const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('overlayApi', {
    getCharacters: () => ipcRenderer.invoke('overlay-get-characters'),
    getHotkey: () => ipcRenderer.invoke('get-overlay-hotkey'),
    getMods: (characterName) => ipcRenderer.invoke('overlay-get-mods', characterName),
    toggleMod: (characterName, modName, enabled) => ipcRenderer.invoke('overlay-toggle-mod', { characterName, modName, enabled }),
    setModMarked: (characterName, modName, marked) => ipcRenderer.invoke('overlay-set-mod-marked', { characterName, modName, marked }),
    triggerReload: () => ipcRenderer.invoke('overlay-trigger-reload'),
    getSettings: () => ipcRenderer.invoke('overlay-get-settings'),
    updateSettings: (updates) => ipcRenderer.invoke('overlay-update-settings', updates),
    applyHotkey: (payload) => ipcRenderer.invoke('overlay-apply-hotkey', payload),
    hideOverlay: () => ipcRenderer.invoke('overlay-hide'),
    openModFolder: (characterName, modName) => ipcRenderer.invoke('open-mod-folder', { characterName, modName }),
    pinMod: (characterName, modName, pinned) => ipcRenderer.invoke('pin-mod', { characterName, modName, pinned }),
    openManagerView: (characterName, modName) => ipcRenderer.invoke('overlay-open-manager-view', { characterName, modName }),
    getPresets: () => ipcRenderer.invoke('overlay-get-presets'),
    activatePreset: (presetName) => ipcRenderer.invoke('overlay-activate-preset', presetName),
    togglePin: (pinned) => ipcRenderer.invoke('overlay-toggle-pin', pinned),
    changeHotkey: (hotkey) => ipcRenderer.invoke('overlay-change-hotkey', hotkey),
    getModDetails: (characterName, modName) => ipcRenderer.invoke('get-mod-details', { characterName, modName }),
    showSide: (opts) => ipcRenderer.invoke('overlay-show-side', opts || {}),
    hideSide: () => ipcRenderer.invoke('overlay-hide-side'),
    updateSide: (content) => ipcRenderer.invoke('overlay-update-side', content),
    resizeOverlay: (scale) => ipcRenderer.invoke('overlay-resize-window', scale),
    onSideContent: (callback) => ipcRenderer.on('side-panel-content', (_, data) => callback(data)),
    selectCharFromSide: (charName) => ipcRenderer.invoke('overlay-select-char-from-side', charName),
    onSelectChar: (callback) => ipcRenderer.on('overlay-char-selected', (_, charName) => callback(charName)),
    resizeSide: (width) => ipcRenderer.invoke('overlay-resize-side', width),
    onCoversChanged: (callback) => ipcRenderer.on('covers-changed', () => callback()),
    onPresetsChanged: (callback) => ipcRenderer.on('presets-changed', () => callback()),
    onGamesChanged: (callback) => ipcRenderer.on('games-changed', (_, data) => callback(data)),
    onWindowShown: (callback) => ipcRenderer.on('overlay-window-shown', () => callback()),
    onOverlayScaleChanged: (callback) => ipcRenderer.on('overlay-scale-changed', (_, data) => callback(data)),
    onMarkedModsChanged: (callback) => ipcRenderer.on('marked-mods-changed', (_, data) => callback(data)),
    onModsChanged: (callback) => ipcRenderer.on('mods-changed', (_, data) => callback(data)),
    fixRunMod: (characterName, modName) => ipcRenderer.invoke('fix:run-mod', { characterName, modName }),
    clearPersistBridgeCache: () => ipcRenderer.invoke('persist-bridge-clear-cache'),
    resetModIni: (characterName, modName) => ipcRenderer.invoke('persist-bridge-reset-mod', { characterName, modName }),
    resetCharacterIni: (characterName) => ipcRenderer.invoke('persist-bridge-reset-character', characterName),
})
